### PR TITLE
Use the htmlName in error messages

### PR DESCRIPTION
**Pull request by cbiesinger**
Otherwise, templates won't display correctly

### CODE REVIEW

**Comment by cbiesinger** [comment]
Is this the right place to do the escaping?

**Comment by sanketj** [comment]
@cbiesinger Do you have an example of this issue?

**Comment by cbiesinger** [comment]
Yeah, see e.g. this screenshot. I had a bug in an extended field, leading to an error message:
Screenshot from 2019-04-19 16-25-16

It should have been `std::__Cr::Map<Foo, Bar, Allocator<....> >`, but the `<Foo` part got interpreted as an HTML Tag.

**Comment by sanketj** [comment]
> Yeah, see e.g. this screenshot. I had a bug in an extended field, leading to an error message:
> Screenshot from 2019-04-19 16-25-16
> 
> It should have been `std::__Cr::Map<Foo, Bar, Allocator<....> >`, but the `<Foo` part got interpreted as an HTML Tag.

Ah, ok. Thanks!

**Comment by petersalas** [comment]
@sanketj I'm a bit late to this party, but shouldn't the downstream code that actually treats the error text as HTML escape it first (or use textContent etc.)

**Comment by sanketj** [comment]
> @sanketj I'm a bit late to this party, but shouldn't the downstream code that actually treats the error text as HTML escape it first (or use textContent etc.)?

@petersalas I actually thought that was deliberate? Sorry, should've asked you first or dug a little deeper...

**Comment by petersalas** [comment]
Nah, should've caught it earlier.  I'll look into it.

**Pull request merged**
